default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  timeout: 5000

development:
  <<: *default
  database: julia_portfolio_development

test:
  <<: *default
  database: julia_portfolio_test

production:
  <<: *default
  adapter: postgresql